# General
spring.application.name=agro-sensores
spring.threads.virtual.enabled=true

# Database H2
spring.datasource.url=jdbc:h2:mem:agrodb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Security JWT
api.security.secret=default-dev-secret-123456
api.security.expiration=2

# SpringDoc/Swagger
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
springdoc.writer-with-default-pretty-printer=true
springdoc.api-docs.resolve-schema-properties=true

# Error details
server.error.include-message=always
server.error.include-stacktrace=always

# Logging
logging.level.root=INFO
logging.level.org.springframework.security=DEBUG
logging.level.org.hibernate.SQL=DEBUG
# === LOGGING AVANÇADO PARA DEBUG DO SPRINGDOC ===
logging.level.org.springdoc=DEBUG
logging.level.org.springdoc.core=DEBUG
logging.level.org.springdoc.api=DEBUG
logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.web.servlet=DEBUG
springdoc.debug=true
springdoc.cache.disabled=true

# Performance
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2

# Timeout
spring.mvc.async.request-timeout=5000